### ISSUE TITLE
HTTP(S) Proxy support

### ISSUE THREAD

**Issue by simfer** [gregorwolf/hanatrial-auth-proxy#2]
Just for testing I’ve create a very simple table on Hanatrial named Employees and I’ve converted it to a service which I can reach successfully using the URL:
https://s6hanaxs.hanatrial.ondemand.com/i045523trial/dev/empdemo/services.xsodata/$metadata
![image](https://cloud.githubusercontent.com/assets/6877529/6541017/3576d738-c4bc-11e4-9782-75ebbf90ee27.png)

Now, I want to use this from SAP Web IDE, so I downloaded your proxy app which I configured in the following way:
![image](https://cloud.githubusercontent.com/assets/6877529/6541024/65eb4f52-c4bc-11e4-8215-06eaa1ec298b.png)

I’m able to start the server:
![image](https://cloud.githubusercontent.com/assets/6877529/6541027/6eb98cac-c4bc-11e4-95e5-d9459375d02b.png)

However when I try to use the link:
http://localhost:7891/i045523trial/dev/empdemo/services.xsodata/$metadata
I’m prompted for credentials and I enter my SCN ones:

![image](https://cloud.githubusercontent.com/assets/6877529/6541028/7c5f0d64-c4bc-11e4-87c2-e3279ea6ec47.png)

After this the page is not loaded and I get the following error in the Terminal window:
![image](https://cloud.githubusercontent.com/assets/6877529/6541030/871bbf4a-c4bc-11e4-8d75-dd36c48e1869.png)

Do you have any idea about why I get this problem? Are you able to help me to debug this issue?
I’ve also tried with another service like: https://s1hanaxs.hanatrial.ondemand.com/s0002687731trial/opensap/perslist/services/pers.xsodata/$metadata
but I’ve got the same results.

Thanks and regards,
Simmaco

**Comment by gregorwolf** [comment]
Hi Simmaco,

the error message getaddrinfo looks to me first like a problem with the DNS lookup of s6hanaxs.hanatrial.ondemand.com. Please check with a ping at least the FQDN is translated in an IP Address. For me it resolves to 155.56.219.22.

Best regards
Gregor

**Comment by simfer** [comment]
Hi Gregor,
I finally found the culprit! Since I was testing it from within the SAP network, it was not working. As soon as I disconnected from the VPN it started working. It seems that this tool is not able to work from behind a firewall. Do you know how to make it working behind a proxy?
Thanks and regards,
Simmaco

**Comment by gregorwolf** [comment]
Hi Simmaco,
in the moment there is no built in support for proxies. I've added it to the TODO section of the readme. Feel free to fork and add this feature :-).
Regards
Gregor

**Comment by gregorwolf** [comment]
Hi Simmaco,
please check the commit c568745c2c4a3484693fa1952254688d572ac3be it should now also work with proxies.
Best regards
Gregor

**Comment by mlenkeit** [comment]
@simfer You will need to maintain the environment variables `HTTP_PROXY` and `HTTPS_PROXY` when you're behind a firewall.

**Comment by gregorwolf** [comment]
@mlenkeit you might have seen that in the [config.js](https://github.com/gregorwolf/hanatrial-auth-proxy/blob/master/examples/config.js) there is an option for proxy. Have you tried and does the request module also supports the environment variables?

**Comment by mlenkeit** [comment]
@gregorwolf as per the docs of the request module, it supports the environment variables:

> The following environment variables are respected by request: ([src](https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables))
> - HTTP_PROXY / http_proxy
> - HTTPS_PROXY / https_proxy
> - NO_PROXY / no_proxy

/cc @simfer

**Comment by gregorwolf** [comment]
OK, I will give it a try later this evening. I would guess that we then have two options. Via the config file and via environment variables.

**Comment by Finkes** [comment]
Did you get it to work with HTTP_PROXY / HTTPS_PROXY? I couldn't and I'm behind a Corporate Proxy as well.

**Comment by amysy** [comment]
Hi Gregor-

I was running server-basic-auth.js and encountered following issues.
C:\Users\Amy\hanatrial-auth-proxy>node service-basic-auth.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Amy\hanatrial-auth-proxy\service-basic-auth.
js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
I tried running this download from the dir where i've node.js libraries but didn't work. 
also tried couple other things such as npm init, and rebuild. but same error is coming up.
I'm also wondering since I've no use for a proxy connection can I jump to cloud connector directly and continue. .
Note: I already made changes to config.js as required.
Suggest.

**Comment by gregorwolf** [comment]
Hi amysy,

please try to run:

```
node server-basic-auth.js
```

from the examples folder. Also you should open a new issue when the topic is not related to an existing issue.

Best regards
Gregor

**Comment by amysy** [comment]
Thanks Greg for your attention. 

Issue is resolved  by another work around.

**Comment by simfer** [comment]
Hi Gregor,
I still couldn't make it working within the SAP network. This is what I tried:
1 - I enabled the proxy line in the config.js file by specifying the correct proxy IP address and port
2 - I set the HTTPS_PROXY and HTTP_PROXY variables in the system
Unfortunately I'm still having this error when doing a request:

```
SAP HANA Cloud Trial Authentication Proxy for HANA XS Services ready: http://localhost:7891
GET /i045523trial/dev/empdemo/services.xsodata/Suppliers
Get new session cookie
{ [Error: tunneling socket could not be established, cause=connect EHOSTUNREACH] code: 'ECONNRESET' }
problem with request: tunneling socket could not be established, cause=connect EHOSTUNREACH
{ [Error: tunneling socket could not be established, cause=connect EHOSTUNREACH] code: 'ECONNRESET' }
```

I'm not sure if I also need the two files proxy-key and proxy-crt because I don't know how to get them.
I hope you can help me.

Thanks and regards,
Simmaco
